#!/usr/bin/env python3
"""Turns model.pt into model_weights.h, the file the sketch compiles in.

gpt.h reads flat float arrays and indexes them by hand, so the order the
weights are written in here is part of the interface: W_qkv is one fused
[q | k | v] matrix per layer, the MLP is fc then fc_proj, and the output head
is tied to W_wte rather than stored separately. Rows are written in row-major
order, which is what matvec() in gpt.h assumes.

The header also carries two hash tables the sketch uses to judge its own
output: GPT_SEEN, the fortunes in the training text, so it can tell when it has
simply memorized one, and GPT_WORDS, every word in the training text, so it can
reject a fortune containing a word it invented. Both are FNV-1a over the same
bytes the sketch hashes, and both are sorted because the sketch looks them up
with a binary search.

    python3 export_header.py                  # model.pt -> ../model_weights.h
    python3 export_header.py --out /tmp/x.h

check_header.py and check_parity.py verify the result.
"""

import argparse
import os

import torch

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# Written in this order; gpt.h declares them in the same order.
LAYOUT = ["W_wte", "W_wpe", "W_ln1_w", "W_ln1_b", "W_qkv", "W_proj",
          "W_ln2_w", "W_ln2_b", "W_fc", "W_fc_proj", "W_lnf_w", "W_lnf_b"]


def fnv1a(s):
    """The sketch's fnv1a(), over the bytes of the string."""
    h = 2166136261
    for b in s.encode("utf-8"):
        h = ((h ^ b) * 16777619) & 0xFFFFFFFF
    return h


def fmt(x):
    """Shortest decimal that still round-trips to the same float32.

    The header is the largest file in the repository, so this matters: %.9g is
    always exact but adds about a third to the size for no gain on the board.
    """
    for p in range(1, 10):
        s = "%.*g" % (p, x)
        if torch.tensor(float(s), dtype=torch.float32).item() == x:
            return s
    return "%.9g" % x


def collect(state, dims):
    """Pulls the tensors out of the checkpoint in gpt.h's flat layout."""
    L = dims["LAYERS"]
    out = {
        "W_wte": state["wte.weight"],
        "W_wpe": state["wpe.weight"],
        "W_lnf_w": state["lnf.weight"],
        "W_lnf_b": state["lnf.bias"],
    }
    # Per-layer tensors are concatenated layer by layer, so gpt.h can reach
    # layer l at offset l * (size of one layer).
    for name, key in (("W_ln1_w", "ln1.weight"), ("W_ln1_b", "ln1.bias"),
                      ("W_ln2_w", "ln2.weight"), ("W_ln2_b", "ln2.bias"),
                      ("W_qkv", "attn.qkv.weight"), ("W_proj", "attn.proj.weight"),
                      ("W_fc", "fc.weight"), ("W_fc_proj", "fc_proj.weight")):
        out[name] = torch.cat([state["blocks.%d.%s" % (l, key)].reshape(-1)
                               for l in range(L)])
    return {k: v.detach().to(torch.float32).reshape(-1) for k, v in out.items()}


def corpus_hashes(path):
    """GPT_SEEN and GPT_WORDS, as the sketch computes them."""
    lines = [l.strip() for l in open(path, encoding="utf-8")]
    lines = [l for l in lines if l]
    seen = sorted(set(fnv1a(l) for l in lines))

    words = set()
    for line in lines:
        w = ""
        for c in line + " ":
            # isalpha() and tolower() in hasMadeUpWord(), same rule.
            if c.isalpha() or c == "'":
                w += c.lower()
            elif w:
                words.add(w)
                w = ""
    return seen, sorted(set(fnv1a(w) for w in words)), len(lines), len(words)


def write_array(f, decl, values, per_line=12):
    f.write("static const float %s = {" % decl)
    for i, v in enumerate(values):
        f.write(("\n  " if i % per_line == 0 else "") + fmt(v) + ("," if i + 1 < len(values) else ""))
    f.write("};\n")


def write_u32(f, decl, values, per_line=8):
    f.write("static const uint32_t %s = {" % decl)
    for i, v in enumerate(values):
        f.write(("\n  " if i % per_line == 0 else "") + "%uu" % v + ("," if i + 1 < len(values) else ""))
    f.write("};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=os.path.join(HERE, "model.pt"))
    ap.add_argument("--corpus", default=os.path.join(HERE, "fortunes.txt"))
    ap.add_argument("--out", default=os.path.join(ROOT, "model_weights.h"))
    args = ap.parse_args()

    ck = torch.load(args.model, map_location="cpu", weights_only=False)
    dims, chars, state = ck["dims"], ck["chars"], ck["model"]
    arrays = collect(state, dims)

    seen, words, n_fortunes, n_words = corpus_hashes(args.corpus)
    total = sum(len(v) for v in arrays.values())

    with open(args.out, "w") as f:
        f.write("// Auto-generated by train.py - do not edit by hand.\n")
        f.write("#pragma once\n#include <stdint.h>\n")
        for k in ("VOCAB", "DIM", "LAYERS", "HEADS", "CTX", "HIDDEN"):
            f.write("#define GPT_%s %d\n" % (k, dims[k]))
        f.write("static const char GPT_CHARS[GPT_VOCAB] = {%s};\n"
                % ",".join(str(ord(c)) for c in chars))
        for name in LAYOUT:
            write_array(f, "%s[%d]" % (name, len(arrays[name])), arrays[name].tolist())
        f.write("#define GPT_SEEN_COUNT %d\n" % len(seen))
        write_u32(f, "GPT_SEEN[GPT_SEEN_COUNT]", seen)
        f.write("#define GPT_WORD_COUNT %d\n" % len(words))
        write_u32(f, "GPT_WORDS[GPT_WORD_COUNT]", words)

    print("wrote %s" % args.out)
    print("  vocabulary  %d characters" % dims["VOCAB"])
    print("  weights     %d floats" % total)
    print("  GPT_SEEN    %d hashes from %d fortunes" % (len(seen), n_fortunes))
    print("  GPT_WORDS   %d hashes from %d distinct words" % (len(words), n_words))
    print("  size        %.2f MB" % (os.path.getsize(args.out) / 1048576.0))


if __name__ == "__main__":
    main()
