#!/usr/bin/env python3
"""Turn a plain list of blocked terms into blocklist_data.h for the sketch.

The header holds only 32-bit FNV-1a hashes of the normalised terms, sorted so
the sketch can binary-search them the same way it searches GPT_SEEN and
GPT_WORDS. Hashes keep the table small (4 bytes a term instead of the ~10 the
strings would take) and keep the word list itself out of the firmware image.

  python3 tools/make_blocklist.py tools/blocklist_en.txt \
      tools/blocklist_allow.txt > blocklist_data.h

The second file is optional: terms listed there are left out of the table, for
ordinary words the fortunes are allowed to use.

A term is normalised the same way the sketch normalises a fortune: lower-case,
every character that is not a letter, a digit or an apostrophe becomes a space,
and runs of spaces collapse to one. So "Zippo-Cat" and "zippo cat" are the same
term, and a term matches only on whole words.
"""
import sys

# Characters the model can emit (GPT_CHARS in model_weights.h). Terms that need
# anything else - the digits in "2 girls 1 cup", say - are unreachable and left out.
VOCAB = set(" '-.,;\n" + "".join(chr(c) for c in range(ord('a'), ord('z') + 1)))


def normalize(term):
    out = []
    for ch in term.lower():
        out.append(ch if (ch.isalnum() or ch == "'") else ' ')
    return ' '.join(''.join(out).split())


def fnv1a(s):
    h = 2166136261
    for b in s.encode('utf-8'):
        h = ((h ^ b) * 16777619) & 0xFFFFFFFF
    return h


def read_terms(path):
    lines = [line.strip() for line in open(path, encoding='utf-8')]
    return [t for t in lines if t and not t.startswith('#')]


def main():
    if not 2 <= len(sys.argv) <= 3:
        sys.exit("usage: make_blocklist.py <terms.txt> [allowed.txt]")

    raw = read_terms(sys.argv[1])
    allowed = {normalize(t) for t in read_terms(sys.argv[2])} if len(sys.argv) == 3 else set()

    terms, unreachable, kept_back = set(), 0, 0
    for term in raw:
        norm = normalize(term)
        if not norm:
            continue
        if norm in allowed:
            kept_back += 1
            continue
        if not set(norm) <= VOCAB:
            unreachable += 1
            continue
        terms.add(norm)

    max_words = max(len(t.split()) for t in terms)
    hashes = sorted(fnv1a(t) for t in terms)
    if len(set(hashes)) != len(hashes):
        sys.exit("hash collision in the term list - change the hash or the terms")

    w = sys.stdout.write
    w("// Auto-generated by tools/make_blocklist.py - do not edit by hand.\n")
    w("// %d terms from %s (%d read, %d left unblocked as ordinary words, %d\n"
      "// dropped as unreachable by the model's character set, the rest\n"
      "// duplicates once normalised).\n"
      % (len(terms), sys.argv[1].split('/')[-1], len(raw), kept_back, unreachable))
    w("// Hashes only: the terms themselves are not in the firmware image.\n")
    w("#pragma once\n#include <stdint.h>\n")
    w("#define BLOCK_COUNT %d\n" % len(terms))
    w("#define BLOCK_MAX_WORDS %d\n" % max_words)
    w("static const uint32_t BLOCK_HASH[BLOCK_COUNT] = {%s};\n"
      % ','.join(str(h) for h in hashes))


if __name__ == '__main__':
    main()
